#! /bin/bash
#------------------------------------------------------------------------------
# bash_profile - Dotfiles bash login profile file.
#
# Copyright (c) 2000-2010 by John Yancey, All rights reserved.
#
# August 2000 John Yancey <john.yancey@acm.org>
#
# $Id$
#------------------------------------------------------------------------------
#
# Bail out early if we started up from an X session. This only seems to be a
# problem on Ubuntu systems. Go figure.
if [ "$GDMSESSION" ]; then
    exit
fi

# Running as a login shell! We have already picked up the path setting 
# from /etc/profile, now get the global aliases and functions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
if

# Use bash_completion, if completion exists
if [ -f /sw/etc/bash_completion ]; then
    . /sw/etc/bash_completion
fi

# Start up key chain server
if [ ! -f $HOME/.nokeychain ]; then
    . $HOME/.files/bashrc_keychain
fi

# Export out all the system information
export OS_SYS=`uname -s`
export OS_REL=`uname -r`
export OS_PLATFORM=`uname -p`
# Figure out which Linux distrabution we are on
if [ $OS_SYS == "Linux" ]; then
    OS_DIST=`/usr/bin/lsb_release -d | sed -e 's/Description:.//'`
    OS_DIST_NAME=`/usr/bin/lsb_release -i | sed -e 's/Distributor ID:.//'`
    export OS_DIST
    export OS_DIST_NAME
fi
export EDITOR=vi
export PAGER=less
export LC_ALL=C
export LC_CTYPE=C
export LANG=en_US.ISO-8859-1

if [ "$PS1" ]; then
    if [ "x`tput kbs`" != "x" ]; then # We can't do this with "dumb" terminal
      stty erase `tput kbs`
    fi
    case $TERM in
      xterm*)
          PROMPT_COMMAND='echo -ne "\033]0;${LOGNAME}@${HOSTNAME}: ${PWD}\007"'
          if [ "$TERM" = "xterm-color" ]; then
              export TERM=xterm
          fi
      ;;
      *)
      ;;
    esac
    if [ -e $HOME/.files/bashrc_prompt ]; then
        . $HOME/.files/bashrc_prompt
    else
        export PS1="[\u@\h \W]\\$ "
    fi
fi

# Now for all the tricky stuff
for i in $HOME/.files/profile.d/*.sh ; do
  if [ -r "$i" ]; then
    . $i
  fi
done

umask 022
