#! /bin/bash
#------------------------------------------------------------------------------
# bash_profile - Dotfiles bash login profile file.
#
# Copyright (c) 2000-2011 by John Yancey, All rights reserved.
#
# August 2000 John Yancey <john.yancey@acm.org>
#
# $Id$
#------------------------------------------------------------------------------
#
declare -x POSIXLY_CORRECT=1

# Bail out early if we started up from an X session. This only seems to be a
# problem on Ubuntu systems. Go figure.
if [ "$GDMSESSION" ]; then
    exit
fi

# Running as a login shell! We have already picked up the path setting 
# from /etc/profile, now get the global aliases and functions
if [ -f /etc/bashrc ]; then
    source /etc/bashrc
fi

# Use bash_completion, if completion exists
if [ -f /sw/etc/bash_completion ]; then
    source /sw/etc/bash_completion
fi

# Start up key chain server
if [ ! -f $HOME/.nokeychain ]; then
    source $HOME/.files/bashrc_keychain
fi

# Export out all the system information
declare -x OS_SYS=`uname -s`
declare -x OS_REL=`uname -r`
declare -x OS_PLATFORM=`uname -p`

# Setup the basices then bail ou if Windoze.
if [ $OS_SYS == "CYGWIN_NT-6.1-WOW64" ]; then
    eval "$(dircolors -b $HOME/.dir_colors)"
    if [ -f /etc/bash_completion ]; then
    source /etc/bash_completion
    fi
    source $HOME/.files/bashrc_prompt
    # Some shortcuts for different directory listings
    alias ls='ls -hF --color=tty'                 # classify files in colour
    alias dir='ls --color=auto --format=vertical'
    alias vdir='ls --color=auto --format=long'
    alias ll='ls -l'                              # long list
    alias la='ls -A'                              # all but . and ..
    alias l='ls -CF'
    echo -ne "\e]2;$@\a\e]1;$@\a";
    declare -x PATH=$PATH:/usr/gnu/bin
    return
fi

# Figure out which Linux distrabution we are on
if [ $OS_SYS == "Linux" ]; then
    OS_DIST=`/usr/bin/lsb_release -d | sed -e 's/Description:.//'`
    OS_DIST_NAME=`/usr/bin/lsb_release -i | sed -e 's/Distributor ID:.//'`
    declare -x OS_DIST
    declare -x OS_DIST_NAME
fi
declare -x EDITOR=vi
declare -x PAGER=less
declare -x LC_ALL=C
declare -x LC_CTYPE=C
declare -x LANG=en_US.ISO-8859-1

if [ "$PS1" ]; then
    if [ "x`tput kbs`" != "x" ]; then # We can't do this with "dumb" terminal
      stty erase `tput kbs`
    fi
    case $TERM in
      xterm*)
          PROMPT_COMMAND='echo -ne "\033]0;${LOGNAME}@${HOSTNAME}: ${PWD}\007"'
          if [ "$TERM" = "xterm-color" ]; then
              declare -x TERM=xterm
          fi
      ;;
      *)
      ;;
    esac
    if [ -e $HOME/.files/bashrc_prompt ]; then
        source $HOME/.files/bashrc_prompt
    else
        declare -x PS1="[\u@\h \W]\\$ "
    fi
fi

# Now for all the tricky stuff
for EXTRAS in $HOME/.files/profile.d/*.sh ; do
  if [ -r "$EXTRAS" ]; then
    source $EXTRAS
  fi
done

umask 022
