#! /bin/bash
#------------------------------------------------------------------------------
# bash_logout - Dotfiles bash logout file.
#
# Copyright (c) 2000-2009 by John Yancey, All rights reserved.
#
# August 2000 John Yancey <john.yancey@acm.org>
#
# $Id$
#------------------------------------------------------------------------------
#
#cvs update
clear
