#! /bin/bash
#------------------------------------------------------------------------------
# bashrc_keychain - Dotfiles.
#
# Copyright (c) 2000-2019 by John Yancey, All rights reserved.
#
# August 2000 John Yancey <john.yancey@acm.org>
#
# $Id$
#------------------------------------------------------------------------------
#
# Start up a keychain agent to avoid crazy password challenge all the time
#
# Set a default keychain
declare -x HOSTNAME=`uname -n`

if [ "$OS_SYS" == "Linux" ]; then
    if [ "$DEBUG" ]; then
        echo "Looking for keychain..."
    fi
    if [ ! -x "/usr/bin/keychain" ]; then
        echo "Unable to find keychain!"
        return
    else
        KEYCHAIN=/usr/bin/keychain
    fi
fi
if [ "$OS_SYS" == "Darwin" ]; then
    if [ "$DEBUG" ]; then
        echo "Looking for keychain..."
    fi
    if [ ! -x "/usr/local/bin/keychain" ]; then
        echo "Unable to find keychain!"
        return
    else
        KEYCHAIN=/usr/local/bin/keychain
   fi
fi

# If the file $HOME/.nokeychain exists, don't run keychain
if [ -e $HOME/.nokeychain ]; then
    echo "Skipping keychain"
    declare -x keychainON=1
fi

# The 'keychainHOSTS' variable is a list of hostnames we really
# want to run keychain agent on. The " _" is a placeholder to ensure 
# there is no empty variable.
keychainHOSTS=" _" 
echo "$keychainHOSTS" | grep `echo $HOSTNAME` > /dev/null

# Run it
if [ "$keychainON" != 0 ]; then
    $KEYCHAIN -q $HOME/.ssh/id_rsa > /dev/null
    source $HOME/.keychain/${HOSTNAME}-sh
fi
