#! /bin/bash
#------------------------------------------------------------------------------
# bashrc_prompt - Dotfiles bash login prompt file.
#
# Copyright (c) 2000-2011 by John Yancey, All rights reserved.
#
# August 2000 John Yancey <john.yancey@acm.org>
#
# $Id$
#------------------------------------------------------------------------------
#
# Define ANSI color sequences
NO="\[\033[0m\]"      # Normal
WH="\[\033[0;37m\]"   # White
MA="\[\033[0;35m\]"   # Magenta
LY="\[\033[0;33m\]"   # Yellow
LR="\[\033[0;31m\]"   # Red
CN="\[\033[0;36m\]"   # Cyan
BR="\[\033[1;31m\]"   # Bright Red
BB="\[\033[1;34m\]"   # Bright Blue
BW="\[\033[1;37m\]"   # Bright White
BM="\[\033[1;35m\]"   # Bright Magenta
BY="\[\033[1;33m\]"   # Bright Yellow

# Find out if we are root
if [ $UID -eq 0 ] ; then
   # The '#' character serves as an extra reminder that I am root
   SYM='#'
else
   SYM='-'
fi

# Define the actual prompt, which will look like:
# --[login@hostname]--
# --{~}--
# --(0)->$
#
#P1="$MA$SYM$BM-$BB[$WH\u$MA@$WH\h$BB]$BM-$MA$SYM$NO\n"
#P2="$MA$SYM$BM-$BB{$BW\w$BB}$BM-$MA$SYM$NO\n"
#P3="$MA$SYM$BM-$BB($BW\$?$BB)$BM-$MA>$NO\$ "

# Define the actual prompt, which will look like:
# --[login@hostname]-- --{~}--
# -->$
#
#P1="$MA$SYM$BM-$BB[$WH\u$MA@$WH\h$BB]$BM-$MA$SYM$NO "
#P2="$MA$SYM$BM-$BB{$BW\W$BB}$BM-$MA$SYM$N0\n"
#P3="$MA$SYM$BM-$BB>$NO\$ "
#declare -x PS1="$P1$P2$P3"

# Define the actual prompt, which will look like:
# [login@hostname]$
#declare -x PS1="$NO$BB[$WH\u$MA@$WH\h$BB]$NO\$ "

# Super simple prompt
# [~/abspath]
# <login@hostname>$
declare -x PS1="$MA[\w]$NO\n$LY<\u@\h>$LR\$$NO "
