#! /bin/sh
#------------------------------------------------------------------------------
# bashrc_keychain - Dotfiles.
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license in  the LICENSE file
# or https://opensource.org/license/cddl-1-0/
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright (c) 2000-2023 by John Yancey, All rights reserved.
#
# August 2000 John Yancey <john.w.yancey@gmail.org>
#
# $Id$
#------------------------------------------------------------------------------
#
# Start up a keychain agent to avoid crazy password challenges all the time
#
# Keys to add to agent:
ssh_keys=(
  aws.pem \
  id_ed25519 \
  id_rsa \
  john-Gitea \
  john.yancey-Bitbucket \
  jyancey-GitHub
)

# Set a default keychain
declare -x HOSTNAME=`hostname -s`

if [[ "${OS_SYS}" == "SunOS" ]]; then
  if [[ "${DEBUG}" ]]; then
    echo "Looking for keychain..."
  fi
  if [[ ! -x "/usr/local/bin/keychain" ]]; then
    echo "Unable to find keychain!"
    return
  else
    declare -x KEYCHAIN=/usr/local/bin/keychain
  fi
fi
if [[ "${OS_SYS}" == "FreeBSD" ]]; then
  if [[ "${DEBUG}" ]]; then
    echo "Looking for keychain..."
  fi
  if [[ ! -x "/usr/local/bin/keychain" ]]; then
    echo "Unable to find keychain!"
    return
  else
    declare -x KEYCHAIN=/usr/local/bin/keychain
  fi
fi
if [[ "${OS_SYS}" == "Linux" ]]; then
  if [[ "${DEBUG}" ]]; then
    echo "Looking for keychain..."
  fi
  if [[ ! -x "/usr/bin/keychain" ]]; then
    echo "Unable to find keychain!"
    return
  else
    declare -x KEYCHAIN=/usr/bin/keychain
  fi
fi
if [[ "${OS_SYS}" == "Darwin" ]]; then
  if [ "${DEBUG}" ]; then
    echo "Looking for keychain..."
  fi
  if [[ -x "/opt/homebrew/bin/keychain" ]]; then
    declare -x KEYCHAIN=/opt/homebrew/bin/keychain
  elif [[ -x "/opt/macports/bin/keychain" ]]; then
    declare -x KEYCHAIN=/opt/macports/bin/keychain
  elif [[ -x "/usr/local/bin/keychain" ]]; then
    declare -x KEYCHAIN=/usr/local/bin/keychain
  else
    echo "Unable to find keychain!"
    return
  fi
fi

# If the file $HOME/.nokeychain exists, don't run keychain
if [[ -e "${HOME}/.nokeychain" ]]; then
  echo "Skipping keychain"
  declare -x keychainON=1
fi

# The 'keychainHOSTS' variable is a list of hostnames we really
# want to run keychain agent on. The " _" is a placeholder to ensure
# there is no empty variable.
keychainHOSTS="lappy"
echo "${keychainHOSTS}" | grep `echo ${HOSTNAME}` > /dev/null

# Run it
if [[ "${keychainON}" != 0 ]]; then
  for ssh_key in "${ssh_keys[@]}"; do
    if [ "${DEBUG}" ]; then
      echo " ---> keychain add $ssh_key..."
    fi
    if [[ -f "$HOME/.ssh/$ssh_key" ]]; then
      if [[ $OS_SYS = 'FreeBSD' ]]; then
	    ${KEYCHAIN} -q --gpg2 $HOME/.ssh/$ssh_key > /dev/null
	  else
        ${KEYCHAIN} -q --gpg2 --ssh-allow-gpg $HOME/.ssh/$ssh_key > /dev/null
	  fi
    fi
  done
  source ${HOME}/.keychain/${HOSTNAME}-sh
fi
